export default {
  bundles: {
    bundle: "mdi-group",
    bundleDate: "mdi-truck-delivery-outline",
  },
  grouping: {
    juniors: "mdi-human-child",
    seniors: "mdi-human-handsup",
    masters: "mdi-human-cane",
    other: "mdi-map-marker",
  },
  navigation: {
    home: "mdi-home",
    eye: "mdi-eye",
  },
  assets: {
    download: "mdi-download",
    file: "mdi-file",
    articles: "mdi-newspaper",
  },
  categories: {
    results: "mdi-scoreboard-outline",
    ladder: "mdi-ladder",
    bowling: "mdi-baseball",
    batting: "mdi-cricket",
    upcoming: "mdi-calendar-text-outline",
    singleResult: "mdi-scoreboard",
    roster: "mdi-format-list-bulleted-square",
  },
  media: {
    video: "mdi-video",
    videoOff: "mdi-video-off",
    createImage: " mdi-image-plus",
  },
  ui: {
    tick: "mdi-check",
    cross: "mdi-close",
    table: "mdi-table",
    currency: "mdi-currency-usd",
    date: "mdi-calendar",
    grades: "mdi-school",
    add: "mdi-plus",
    sync: "mdi-sync",
    extLink: "mdi-link",
    save: "mdi-content-save",
    edit: "mdi-pencil",
    delete: "mdi-delete",
    addPlayer: "mdi-account-plus",
    player: "mdi-account",
  },
  charts: {
    chart: "mdi-chart-bar",
    pieChart: "mdi-chart-pie",
    lineChart: "mdi-chart-line",
  },
  arrowRight: "mdi-arrow-right",

  minus: "mdi-minus",
  close: "mdi-close",
  menu: "mdi-menu",

  logout: "mdi-logout",
  settings: "mdi-cog",
  search: "mdi-magnify",
  filter: "mdi-filter",
  sort: "mdi-sort",
  edit: "mdi-pencil",
  delete: "mdi-delete",

  cancel: "mdi-cancel",
  refresh: "mdi-refresh",

  dashboard: "mdi-view-dashboard",
  calendar: "mdi-calendar",
  clock: "mdi-clock",
  email: "mdi-email",
  phone: "mdi-phone",

  share: "mdi-share-variant",
  info: "mdi-information",
  warning: "mdi-alert",
  error: "mdi-alert-circle",
  success: "mdi-check-circle",
  upload: "mdi-upload",
  image: "mdi-image",
  video: "mdi-video",
  audio: "mdi-music",
  folder: "mdi-folder",
  star: "mdi-star",
  heart: "mdi-heart",
  thumbUp: "mdi-thumb-up",
  thumbDown: "mdi-thumb-down",
  comment: "mdi-comment",
  send: "mdi-send",
  print: "mdi-printer",
  lock: "mdi-lock",
  unlock: "mdi-lock-open",

  eyeOff: "mdi-eye-off",
  arrowLeft: "mdi-arrow-left",
  arrowUp: "mdi-arrow-up",
  arrowDown: "mdi-arrow-down",
  chevronRight: "mdi-chevron-right",
  chevronLeft: "mdi-chevron-left",
  chevronUp: "mdi-chevron-up",
  chevronDown: "mdi-chevron-down",
  play: "mdi-play",
  pause: "mdi-pause",
  stop: "mdi-stop",
  fastForward: "mdi-fast-forward",
  rewind: "mdi-rewind",
  repeat: "mdi-repeat",
  shuffle: "mdi-shuffle",
  volume: "mdi-volume-high",
  mute: "mdi-volume-off",
  bell: "mdi-bell",
  bellOff: "mdi-bell-off",
  bookmark: "mdi-bookmark",
  bookmarkOutline: "mdi-bookmark-outline",
  tag: "mdi-tag",
  tags: "mdi-tag-multiple",
  attachment: "mdi-paperclip",
  camera: "mdi-camera",
  microphone: "mdi-microphone",
  wifi: "mdi-wifi",
  bluetooth: "mdi-bluetooth",
  battery: "mdi-battery",
  map: "mdi-map-marker",
  compass: "mdi-compass",
  cloud: "mdi-cloud",
  cloudUpload: "mdi-cloud-upload",
  cloudDownload: "mdi-cloud-download",

  history: "mdi-history",
  undo: "mdi-undo",
  redo: "mdi-redo",
  zoomIn: "mdi-magnify-plus",
  zoomOut: "mdi-magnify-minus",
  fullscreen: "mdi-fullscreen",
  exitFullscreen: "mdi-fullscreen-exit",
  copy: "mdi-content-copy",
  paste: "mdi-content-paste",
  cut: "mdi-content-cut",
  archive: "mdi-archive",
  unarchive: "mdi-unarchive",
  flag: "mdi-flag",
  favorite: "mdi-star",
  favoriteOutline: "mdi-star-outline",
  trash: "mdi-delete",
  restore: "mdi-restore",
  shoppingCart: "mdi-cart",
  creditCard: "mdi-credit-card",
  gift: "mdi-gift",
  ticket: "mdi-ticket",
  qrCode: "mdi-qrcode",
  barcode: "mdi-barcode",
  language: "mdi-translate",
  globe: "mdi-earth",
  palette: "mdi-palette",
  brush: "mdi-brush",
  formatBold: "mdi-format-bold",
  formatItalic: "mdi-format-italic",
  formatUnderline: "mdi-format-underline",
  formatStrikethrough: "mdi-format-strikethrough",
  formatListBulleted: "mdi-format-list-bulleted",
  formatListNumbered: "mdi-format-list-numbered",
  formatAlignLeft: "mdi-format-align-left",
  formatAlignCenter: "mdi-format-align-center",
  formatAlignRight: "mdi-format-align-right",
  formatAlignJustify: "mdi-format-align-justify",
  unlink: "mdi-link-off",
};
